### ISSUE TITLE
I can't use the mask in AnimAide

### ISSUE THREAD

**Issue by MeguiTaA12** [aresdevo/animaide#100]
Error
This error happens when I click on the mask button in the addon itself

Python: Traceback (most recent call last):

File "C:\Users\megag\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\animaide-master\anim_offset\[ops.py](https://ops.py/)", line 402, in modal

support.set_blend_values(context)

File "C:\Users\megag\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\animaide-master\anim_offset\[support.py](https://support.py/)", line 201, in set_blend_values

keys[1].co.x = left_margin

IndexError: bpy_prop_collection[index]: index 1 out of range, size 1
![2024-03-14_01-44](https://github.com/aresdevo/animaide/assets/157763009/edbd3c11-6a12-44ed-b211-f60bb87eb722)

**Comment by Sobollion** [comment]
Answer is [here](https://github.com/aresdevo/animaide/issues/98#issuecomment-1974850006)

**Comment by cl3m3c7** [comment]
I merged some of @Sobollion 's commits, fixed the current issue and added blender_manifest.toml to work with blender v4.2+
