### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by CGMikeG** [aresdevo/animaide#54]
Hi, not sure why this isn't working now.

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\Venice\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animaide-3_0_33\curve_tools\ops.py", line 202, in invoke
    support.get_globals(context)
  File "C:\Users\Venice\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animaide-3_0_33\curve_tools\support.py", line 173, in get_globals
    if not utils.curve.valid_fcurve(context, obj, fcurve):
  File "C:\Users\Venice\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animaide-3_0_33\utils\curve.py", line 337, in valid_fcurve
    bone_name = split_data_path[1]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by CGMikeG** [comment]
I deleted all copies of the addon in all the other blender versions and that solve the issue.
