### ISSUE TITLE
AttributeError happens on some files

### ISSUE THREAD

**Issue by Likkkez** [aresdevo/animaide#9]
```
Traceback (most recent call last):
  File "/home/dmitriy/.config/blender/2.81/scripts/addons/animaide-master/ui.py", line 156, in draw
    key_utils.get_sliders_globals()
  File "/home/dmitriy/.config/blender/2.81/scripts/addons/animaide-master/key_utils.py", line 436, in get_sliders_globals
    if not valid_fcurve(fcurve):
  File "/home/dmitriy/.config/blender/2.81/scripts/addons/animaide-master/key_utils.py", line 387, in valid_fcurve
    if fcurve.group.name == cur_utils.group_name:
AttributeError: 'NoneType' object has no attribute 'name'

```
I've tried to replicate it but I have no idea why this happens. It just consistently happens on some of my animation files and the addon stops working. It might be because some of my animations have tracks for bones that no longer exist but thats all i got.

**Comment by aresdevo** [comment]
This seems to suggest there are f-curves without groups in your character. It is something I was not expecting to ever be the case because the groups represent the bones in a character. Anyway, I added a bit of code to overcome that. Hopefully it works. Let me know

**Comment by Likkkez** [comment]
This seems to have fixed my issues! Thank you!

**Comment by aresdevo** [comment]
Glad it worked. It would seem your guess was a very good one. Glad you brought it up, I didn't  think of that scenario.
